---@meta

-- GENERATED by tools/gen-docs.js from api.lua and the source. DO NOT EDIT.
--
-- `npm run docs` regenerates this and API.md; `npm run docs:check` fails if
-- either committed copy is stale. Editing this by hand produces a stub that
-- LIES to every consumer who trusts it, which is worse than no stub at all.

-- NOT loaded by fxmanifest and must never be: annotations, no executable code.

local cis_bridge = {}

-- One class per export, carrying the same metadata api.lua declares. The
-- `use` field doubles as the migration note: it is what an integrator reads
-- on seeing `deprecated` and wondering what to do about it.
---@deprecated
---@class cis_bridge.CisBridgeDatabaseGhmatti
---@field use string ghmattimysql, deprecated upstream. Present so installing the bridge does not break the last server still running it
---@field since string 1.0.0
---@field deprecated boolean true
---@field realm string server
function cis_bridge.CisBridgeDatabaseGhmatti() end

---@class cis_bridge.CisBridgeDatabaseMongodb
---@field use string mongodb. Registers so the platform can say it does not support MongoDB, rather than reporting a missing database capability
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeDatabaseMongodb() end

---@class cis_bridge.CisBridgeDatabaseMysqlConnector
---@field use string mysql-connector. Callback-first, bridged to await with a hard deadline. Refuses a transaction rather than faking one. NOT mysql-async, which is a different export set
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeDatabaseMysqlConnector() end

---@class cis_bridge.CisBridgeDatabaseOxmysql
---@field use string oxmysql. The only target that supports Cis.db.transaction. Probes for the single/query exports and falls back, so an older build still serves both
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeDatabaseOxmysql() end

---@class cis_bridge.CisBridgeDiscord
---@field use string Discord webhooks. The ONLY outbound network request in the platform, which is why it is a file here rather than a function in a library
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeDiscord() end

---@class cis_bridge.CisBridgeFrameworkClient
---@field use string Client framework capability: ShowNotification and IsLoaded only. No Notify -- a client cannot address a player
---@field since string 1.2.0
---@field deprecated boolean false
---@field realm string client
function cis_bridge.CisBridgeFrameworkClient() end

---@class cis_bridge.CisBridgeFrameworkServer
---@field use string Server framework capability: NormalizedPlayer, Notify, IsLoaded, HasPermission, GetPlayerJob. Falls back to it only when no other resource provides one
---@field since string 1.2.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeFrameworkServer() end

---@class cis_bridge.CisBridgeInventoryCodem
---@field use string codem-inventory. The only one with no boolean in its contract: HasItem and AddItem answer counts and nil
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeInventoryCodem() end

---@class cis_bridge.CisBridgeInventoryOx
---@field use string ox_inventory. GPL-3.0: isolated in this one file, never vendored, never modified
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeInventoryOx() end

---@class cis_bridge.CisBridgeInventoryQb
---@field use string qb-inventory. Takes no metadata, and reports refusal as a STRING -- both differ from the others and neither can be a flag
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeInventoryQb() end

---@class cis_bridge.CisBridgeInventoryQs
---@field use string qs-inventory
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.CisBridgeInventoryQs() end

---@class cis_bridge.CisBridgeTargetOx
---@field use string ox_target. Registered only when ox_target is started AND the configured target is ox_target
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string client
function cis_bridge.CisBridgeTargetOx() end

---@class cis_bridge.CisBridgeTargetQb
---@field use string qb-target. Takes a box zone as three numbers where ox_target takes a vector3, which is why it cannot be a flag on the other one
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string client
function cis_bridge.CisBridgeTargetQb() end

---@class cis_bridge.GetBridgeReport
---@field use string One row per adapter slot: { slot, label, target, detail, fix }. The same content the boot printout shows, so another resource can render it
---@field since string 1.1.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.GetBridgeReport() end

---@class cis_bridge.GetConformanceResults
---@field use string The last run, as an array of { target, name, ok, skipped, detail }. For a support thread
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.GetConformanceResults() end

---@class cis_bridge.GetDbProxy
---@field use string The legacy MySQL / oxmysql surface over cis_libs' Db* exports, including the transaction bind-key normalisation
---@field since string 1.2.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.GetDbProxy() end

---@class cis_bridge.GetLibShim
---@field use string ox_lib's lib.callback and lib.zones over cis_libs. A zone size is passed through UNCHANGED because CreateZone halves it itself
---@field since string 1.2.0
---@field deprecated boolean false
---@field realm string server
function cis_bridge.GetLibShim() end

---@class cis_bridge.RunConformance
---@field use string The same as the cis_bridge console command. Runs every registered target, or one named. Sends nothing and writes nothing to a player
---@field since string 1.0.0
---@field deprecated boolean false
---@field realm string server
---@param target any
function cis_bridge.RunConformance(target) end

return cis_bridge
