-- The seam between this resource and cis_libs.
--
-- An adapter's whole job is: check whether my target is actually running, and
-- if it is, register myself as the capability. That is small enough to be one
-- helper, and small enough that every adapter MUST use it rather than
-- hand-rolling the same four lines.
--
-- The four lines matter more than they look:
--
--   1. Is the resource started? An adapter that registers against a target
--           that is not there is an adapter whose every call raises.
--   2. Does the configured name match? A server with ox_target installed but
--      configured for qb-target should use neither, and should be told so --
--      "the target you configured is not installed" is a different problem
--      from "no target is installed", and the operator needs to be told which.
--   3. Does the export we need exist? Older oxmysql has no `single`; a
--      feature probe beats calling it and catching the raise on every query.
--   4. Register, and say so. A silent registration is a registration nobody
--      can debug.

Bridge = {}

--- How long an adapter waits for its target to START, in milliseconds.
---
--- Not a preference. `ensure cis_bridge` above `ensure ox_target` is an
--- extremely common server.cfg, and an adapter that checks once and gives up
--- does not register for the lifetime of the process -- so the platform works
--- on the machine where the author tested it and silently has no target on half
--- the servers that install it. Waiting is what makes start order irrelevant,
--- which is the same property cis_libs builds for its own ready gate and
--- capability waits.
---
--- Bounded, because an adapter that waited forever would report nothing at all
--- on a server where the target genuinely is not installed, and "this resource
--- registered nothing" is the single most useful sentence a support thread gets.
Bridge.WAIT_MS = 60000

--- How often to re-check while waiting. 500ms is fast enough that a target
--- which takes two seconds to come up feels instant, and slow enough that ten
--- adapters waiting together cost twenty wakeups a second for that window.
Bridge.POLL_MS = 500

local registered = {}
local outcomes = {}

--- The fix for an operator, named per slot.
---
--- Kept here, above every function that uses it, rather than below: a `local
--- function` declared after its caller is not in that caller's scope at all, so
--- `register` would be reading a GLOBAL named `fixFor`, find nil, and the one
--- path that exists to turn a refusal into an instruction would raise instead --
--- turning "here is how to fix it" into a stack trace on exactly the servers
--- that need the instruction.
---
--- This is part of the DECISION, not of the report. An adapter that does not
--- register is not a bug, and the sentence that explains it is part of the
--- product. "Not registered" with no next step is a support ticket.
local FIXES = {
    target = 'install and start ox_target or qb-target, or set Framework.Target.Type to the '
        .. 'one you use in your config file',
    database = 'install and start oxmysql, mysql-connector, ghmattimysql or mongodb, and set '
        .. 'Framework.Database.Type to it (AUTO picks whatever is started)',
    inventory = 'install and start ox_inventory, qb-inventory, qs-inventory or '
        .. 'codem-inventory, and set Framework.Inventory to the one you use',
    discord = 'this adapter needs no third-party resource; it registers on its own',
}

--- The next step for a slot that did not register, or nil when there is none to
--- suggest. `wanted` is the name the configuration asked for, when it asked for
--- something other than what is running.
local function fixFor(slot, wanted)
    if wanted and type(wanted) == 'string' and wanted ~= '' then
        return ('the server is configured for %q. Start %s, or change the configuration '
            .. 'to the one you use'):format(tostring(wanted), tostring(wanted))
    end
    return FIXES[slot]
end

-- WHY A REFUSAL NEEDS CLASSIFYING RATHER THAN ONE SENTENCE
--
-- `RegisterCapability` refuses for reasons that need opposite fixes, and a single
-- canned answer for all of them is worse than none:
--
--   - cis_libs refuses a resource that is not in `Security.AuthorizedResources`.
--     Since 2.2.0 an EMPTY list is ALWAYS restrictive, so this is what a stock
--     install gets by default. The fix is one line of configuration.
--   - cis_libs refuses a second registrant because the slot is already held. The
--     fix is to stop the other resource.
--
-- Telling the first case to "stop the other one" sends an operator looking for a
-- resource that does not exist while the actual answer -- add this line to your
-- config -- is never said out loud. That is precisely the ticket the boot report
-- exists to prevent, generated by the boot report itself.
--
-- The classification reads cis_libs' own words because that string is its
-- DOCUMENTED refusal format: "cis_libs refused <export> from <resource>: add
-- '<resource>' to Security.AuthorizedResources". Matching it is not a guess --
-- it is reading the contract. Anything unrecognised falls through to
-- "something else", which passes cis_libs' own sentence through as the fix
-- rather than replacing it with an opinion.
local function classifyRefusal(why)
    local text = type(why) == 'string' and why or ''
    if text:find('AuthorizedResources', 1, true) then
        return 'not_authorized'
    end
    if text:find('already registered', 1, true) then
        return 'held_elsewhere'
    end
    return 'refused'
end

local function fixForRefusal(slot, why)
    local kind = classifyRefusal(why)
    if kind == 'not_authorized' then
        local here = GetCurrentResourceName()
        return ('cis_libs will not let %s fill a slot until it is authorised, and since '
            .. 'cis_libs 2.2.0 an EMPTY allow-list refuses everything. Add this line to the '
            .. 'config of the resource that configures cis_libs (cis_core by default) and '
            .. 'restart it:  Security.AuthorizedResources = { %q, ... }')
            :format(here, here)
    end
    if kind == 'held_elsewhere' then
        return 'another resource already provides this capability, and only one resource '
            .. 'may provide a slot. Stop the other one, or remove cis_bridge if that is '
            .. 'the resource you did not mean'
    end
    -- Unrecognised. cis_libs said something this file has not seen before, and its
    -- sentence is more informative than anything invented here would be.
    return ('cis_libs refused the registration and this version of cis_bridge does not '
        .. 'recognise the reason. cis_libs said: %s'):format(tostring(why))
end

--- Every adapter that has ATTEMPTED to register, in a fixed order, so the boot
--- report prints the same lines in the same sequence on every server. A report
--- whose order depends on which thread happened to win is a report that cannot
--- be diffed between two runs.
Bridge.SLOTS = {
    { slot = 'target', label = 'target' },
    { slot = 'database', label = 'database' },
    { slot = 'inventoryProvider', label = 'inventory' },
    { slot = 'discord', label = 'discord' },
}

--- Is a third-party resource actually running?
function Bridge.started(name)
    return GetResourceState(name) == 'started'
end

--- Wait for a resource to reach 'started', or for the wait to run out.
---
--- 'missing' answers immediately and without waiting: FiveM reports 'missing'
--- for a resource that is not installed AT ALL, and no amount of waiting will
--- change that. Waiting on it would hold the adapter silent for a minute to
--- report something it already knew, which is the difference between a boot
--- that explains itself and a boot that looks hung.
---
--- 'stopped' is different. It means installed and currently down, which is
--- exactly what a resource that starts after us looks like from here.
local function waitForTarget(name, timeoutMs)
    local deadline = GetGameTimer() + (timeoutMs or Bridge.WAIT_MS)
    while true do
        local state = GetResourceState(name)
        if state == 'started' then
            return true, state
        end
        if state == 'missing' then
            return false, state
        end
        if GetGameTimer() >= deadline then
            return false, state
        end
        Wait(Bridge.POLL_MS)
    end
end

--- Record why a slot did or did not end up registered.
---
--- The boot report is a pure function of this table, which is what makes it
--- possible for the report to say "you configured qb-target and started
--- ox_target" instead of "not registered". Recomputing that from a second pass
--- over the same conditions would be a second implementation of the same rules,
--- and the two would drift.
local function record(slot, entry)
    outcomes[slot] = entry
end

--- What every adapter's registration attempt came to. For the boot report and
--- for `GetBridgeReport()`; the conformance runner uses `registered()`.
function Bridge.outcomes()
    return outcomes
end

--- Register this resource as the provider for a capability.
---
--- `configured` is the operator's choice, read from cis_libs. `nil` means "no
--- opinion" -- an adapter whose target is unambiguous (oxmysql is the only
--- database most servers have) registers on presence alone, and one that
--- competes with a rival (two target resources, two inventory resources)
--- respects the configured name.
---
--- `probeExport` is what the adapter needs the target to HAVE, and it may be a
--- single name or a list of them. The list form exists because one export is
--- not enough to establish compatibility: an adapter that calls six of a
--- target's exports has six ways to be wrong, and probing one of them proves
--- only that the target exists. Every missing name is named, so the console line
--- answers "which" and not merely "no".
---
--- `exportName` is PER ADAPTER and that is not a style choice. Two adapters in
--- one resource registering the same export name means the second silently
--- replaces the first, so whichever file happened to load last answers for
--- every capability -- and a server with ox_target and no qb-target would end
--- up being served by whichever qb adapter ran last, which fails on every call
--- and names a resource that is not even installed. One name per adapter.
---
--- @return boolean registered
function Bridge.register(slot, target, configured, probeExport, exportName)
    -- AUTO IS "NO OPINION", and reading it as a rival resource name is what
    -- stopped a stock install from ever registering a driver. `Database.Type`
    -- ships as "AUTO" in both the config and the library defaults, so every
    -- adapter compared its own name against the string "AUTO", found a
    -- mismatch, and refused -- on a server where oxmysql was running, with
    -- nothing wrong anywhere. AUTO means "work it out from what is started",
    -- which is exactly the presence path a nil already took.
    if configured == 'AUTO' or configured == 'auto' then
        configured = nil
    end
    -- The same sentence, from the other direction. 'NONE' is what
    -- `GetConfigSummary` reports for a slot nobody configured, and it is an
    -- ANSWER rather than a rival: there is no operator choice to respect, so
    -- treating it as one refuses the only driver on the server.
    if configured == 'NONE' or configured == 'none' then
        configured = nil
    end

    -- The configuration is checked BEFORE the wait, because it costs nothing
    -- and answering it first means a server configured for a resource it does
    -- not have is told so at once rather than after a minute of silence.
    if configured and configured ~= '' and configured ~= target then
        local message = ('the configuration names %q'):format(tostring(configured))
        print(('[cis_bridge] %s: not registered, %s'):format(slot, message))
        record(slot, {
            slot = slot, target = target, ok = false,
            reason = 'configured_elsewhere', detail = message, fix = fixFor(slot, configured),
        })
        return false
    end

    local started, state = waitForTarget(target)
    if not started then
        local message, detail, fix
        if state == 'missing' then
            message = ('%s is not installed'):format(target)
            detail = ('%s reports "missing", which means it is not on this server at all'):format(target)
            -- `nil` for the configured name, deliberately. The two branches of
            -- `fixFor` ask different questions -- "the configuration names X, so
            -- start X" and "here is the resource to start" -- and a resource that
            -- is absent is the second question. Passing `target` here answered
            -- the first with a resource nobody configured, so the fix told an
            -- operator to go and start the very thing that is not installed.
            fix = fixFor(slot)
        else
            message = ('%s is %s and did not start within %dms')
                :format(target, tostring(state), Bridge.WAIT_MS)
            detail = ('%s reports %q; it was waited on for %dms')
                :format(target, tostring(state), Bridge.WAIT_MS)
            fix = ('check the start order in server.cfg: put `ensure %s` BEFORE `ensure cis_bridge`')
                :format(target)
        end
        print(('[cis_bridge] %s: not registered, %s'):format(slot, message))
        record(slot, {
            slot = slot, target = target, ok = false,
            reason = (state == 'missing') and 'not_installed' or 'not_started',
            detail = message, fix = fix,
        })
        return false
    end

    if probeExport ~= nil and probeExport ~= '' then
        local required = type(probeExport) == 'table' and probeExport or { probeExport }
        local missing = {}
        -- Read one target table, then index it per name. Reading
        -- `exports[target]` per name would cross the boundary per probe and,
        -- worse, on a stopped resource would RAISE on some names and not others
        -- -- so which names are reported as missing would depend on which of
        -- them happened to raise.
        local okTarget, targetExports = pcall(function()
            return exports[target]
        end)
        for _, name in ipairs(required) do
            local present = false
            if okTarget and targetExports then
                -- The VALUE, not the absence of an error. Indexing a missing
                -- export in FiveM answers nil rather than raising, so a bare
                -- `pcall` around the index records "yes, present" for every
                -- target ever seen -- which is the same mistake that let an
                -- oxmysql adapter take its `single` branch against a build that
                -- had no `single`.
                local okName, fn = pcall(function()
                    return targetExports[name]
                end)
                present = okName and fn ~= nil
            end
            if not present then
                missing[#missing + 1] = tostring(name)
            end
        end
        if #missing > 0 then
            local message = ('%s is started but exposes no %s export')
                :format(target, table.concat(missing, ' or '))
            print(('[cis_bridge] %s: not registered, %s'):format(slot, message))
            record(slot, {
                slot = slot, target = target, ok = false,
                reason = 'missing_export', detail = message,
                fix = ('this build of %s does not export %s. Update it, or install a build '
                    .. 'that does; the adapter refuses to register because every call would raise')
                    :format(target, table.concat(missing, ' or ')),
            })
            return false
        end
    end

    if type(exportName) ~= 'string' or exportName == '' then
        error(('Bridge.register(%s) needs the export name of the calling adapter'):format(slot), 2)
    end
    local provider = GetCurrentResourceName() .. ':' .. exportName
    local ok, why = exports['cis_libs']:RegisterCapability(slot, provider)
    if not ok then
        print(('[cis_bridge] %s: registration REFUSED -- %s'):format(slot, tostring(why)))
        record(slot, {
            slot = slot, target = target, ok = false,
            reason = classifyRefusal(why), detail = tostring(why),
            fix = fixForRefusal(slot, why),
        })
        return false
    end
    registered[slot] = target
    print(('[cis_bridge] %s: %s registered'):format(slot, target))
    record(slot, { slot = slot, target = target, ok = true })
    return true
end

--- What this resource actually registered. The conformance runner reads it, and
--- so does the boot report: "cis_bridge is installed but registered nothing" is
--- a very different sentence from "cis_bridge is not installed".
function Bridge.registered()
    return registered
end

-- The method table each adapter registered, kept here so the conformance runner
-- can test THIS RESOURCE'S OWN CODE rather than whatever capability happens to
-- be answering.
--
-- This is not tidiness. cis_libs routes `Cis.inventory.count` to the
-- `inventory` slot, which cis_core owns, and cis_bridge fills the
-- `inventoryProvider` slot underneath it -- so a conformance suite that calls
-- `Cis.inventory.*` is testing cis_core, and on a server without cis_core
-- installed it reports four failing inventory adapters on a perfectly healthy
-- bridge. Testing the adapter directly is also the more honest question: "does
-- ox_inventory answer the way we assumed" is a fact about ox_inventory, and it
-- should not change because somebody's service layer is missing.
local adapters = {}

--- Publish an adapter's method table after it has registered.
---
--- Called by the adapter itself, immediately after `Bridge.register` answers
--- true, so the two cannot drift: an adapter that registers without publishing
--- is simply absent from the conformance run, and an adapter that publishes
--- without registering is a row that reports on a capability nobody holds.
function Bridge.publish(slot, methods)
    if type(methods) ~= 'table' then
        error(('Bridge.publish(%s) needs the adapter method table'):format(slot), 2)
    end
    adapters[slot] = methods
end

--- The method table registered for a slot, or nil.
function Bridge.adapterFor(slot)
    return adapters[slot]
end

--- The configured third-party names, read through cis_libs so this resource has
--- no config file of its own and cannot disagree with the operator's.
---
--- Read fresh each call rather than cached: an operator editing a config and
--- restarting one resource is a normal thing to do, and a cached answer makes
--- the second restart behave differently from the first for no visible reason.
function Bridge.configured(key)
    local ok, summary = pcall(function()
        return exports['cis_libs']:GetConfigSummary()
    end)
    if not ok or type(summary) ~= 'table' then
        return nil
    end
    return summary[key]
end