#!/usr/bin/env node
'use strict'

// Generates API.md from api.lua and the source.
//
//   node tools/gen-docs.js            write API.md
//   node tools/gen-docs.js --check    fail if API.md is not what would be written
//
// WHY GENERATED AND NOT WRITTEN
//
// The roadmap asks for one contract feeding several consumers: docs, types,
// changelogs, the storefront, the support bot. This is the first of those for
// this resource, and it is generated from the SAME two inputs the api validator
// reads -- api.lua for the declared intent, the source scan for what the code
// actually registers. So:
//
//   - the reference cannot describe an export that was renamed, because the
//     generator reads the source and `npm run test:api` fails on the difference;
//   - it cannot omit an export, because the generator iterates the scan;
//   - a new adapter with no entry in api.lua fails CI BEFORE this file is
//     consulted, which is the correct order.
//
// A hand-written API reference is wrong within two releases. This one is wrong
// only if someone skips the check, and the check is in `npm run test:all`.
//
// WHAT IS DELIBERATELY NOT HERE
//
// No line numbers. A `file.lua:123` in generated documentation is stale the next
// time anybody inserts a line above it, and the only thing that teaches people
// to distrust a reference is a reference that is confidently wrong about where
// things are. The FILE is stable and is what a reader needs.
//
// The header carries the contract major, because `api = 1` is the thing a
// consumer pins against and it is not the product version.

const fs = require('fs')
const path = require('path')
const { loadManifest } = require('./validate-api.js')
const { scanResource } = require('./lua-exports.js')

const ROOT = path.join(__dirname, '..')
const OUT = path.join(ROOT, 'API.md')

function fail(message) {
  process.stderr.write(`${message}\n`)
  process.exit(1)
}

const loaded = loadManifest(path.join(ROOT, 'api.lua'), path.join(ROOT, 'api.lua'))
if (loaded.error) {
  fail(`api.lua did not load: ${loaded.error}`)
}
const api = loaded.table
const surface = scanResource(ROOT)

// The source scan is the truth about what exists; api.lua is the truth about
// what it MEANS. Both are needed, and `npm run test:api` is what asserts they
// agree -- so this generator can assume they do and simply refuse to run if
// either is missing a name, rather than emitting a reference with a hole in it.
const scanned = new Map()
for (const entry of surface.exports || []) {
  scanned.set(entry.name, entry)
}

const out = []
const w = (s = '') => out.push(s)

w('# cis_bridge — API reference')
w()
w('**Generated.** Do not edit this file: it is written from `api.lua` and from')
w('what the resource actually registers, and `npm run docs:check` fails if it')
w('is not what they would produce.')
w()
w(`| | |`)
w(`|---|---|`)
w(`| Product version | \`${api.version}\` |`)
w(`| Contract major | \`api = ${api.api}\` |`)
w(`| Schema | \`${api.schema}\` |`)
w(`| Generated from | \`api.lua\` + a scan of every file the manifest loads |`)
w()
w('---')
w()

// ---------------------------------------------------------------- exports

const byRealm = { server: [], client: [] }
for (const [name, spec] of Object.entries(api.exports || {})) {
  const realm = spec.realm === 'client' ? 'client' : 'server'
  byRealm[realm].push({ name, spec })
}

for (const realm of ['server', 'client']) {
  const list = byRealm[realm]
  if (list.length === 0) continue
  w(`## Exports — ${realm}`)
  w()
  w('```lua')
  w(`exports['cis_bridge']:${list.length === 1 ? list[0].name : '<Name>'}(${list[0].spec.signature || '()'})`)
  w('```')
  w()
  w('| Export | Signature | Since | Stability | Declared in |')
  w('|---|---|---|---|---|')
  for (const { name, spec } of list.sort((a, b) => a.name.localeCompare(b.name))) {
    const found = scanned.get(name)
    // A name declared in api.lua and absent from the source is a CI failure in
    // `npm run test:api` -- E031. Emitting "not found" here as well costs
    // nothing and makes this file usable on its own.
    const where = found ? `\`${found.file}\`` : '**not in the source**'
    const stability = spec.deprecated
      ? `**deprecated** since ${spec.since}`
      : (spec.until === false ? 'stable' : `until ${spec.until}`)
    w(`| \`${name}\` | \`${spec.signature || '()'}\` | ${spec.since} | ${stability} | ${where} |`)
  }
  w()

  for (const { name, spec } of list.sort((a, b) => a.name.localeCompare(b.name))) {
    w(`### \`${name}\``)
    w()
    w(`\`${spec.signature || '()'}\` · ${realm} · since ${spec.since}`
      + (spec.deprecated ? ` · **deprecated**, removed in ${spec.until || 'a future major'}` : ''))
    w()
    w(spec.use)
    w()
  }
}

// ------------------------------------------------------------------ events

w('## Events')
w()
const events = api.events || {}
if (Object.keys(events).length === 0) {
  w('_None published._')
} else {
  for (const [name, spec] of Object.entries(events)) {
    w(`### \`${name}\``)
    w()
    w(`since ${spec.since}`)
    w()
    w(spec.payload)
    w()
  }
}

w('---')
w()
w('**Contract stability.** `api = ' + api.api + '` has not moved. No signature,')
w('argument order or return shape changes without a major bump, and a')
w('deprecation is logged once per calling resource per boot rather than')
w('silently. See [CHANGELOG.md](CHANGELOG.md) for what is deprecated and when.')
w()
w('---')
w()
w('**Author:** Cisoko · **Docs:** <https://docs.cisoko.net> · '
  + '**Discord:** <https://discord.gg/cisoko>')

const text = out.join('\n') + '\n'

// ------------------------------------------------------------------- write

if (process.argv.includes('--check')) {
  if (!fs.existsSync(OUT)) {
    fail('API.md does not exist. Run: npm run docs')
  }
  const current = fs.readFileSync(OUT, 'utf8')
  if (current === text) {
    process.stdout.write('  PASS  API.md matches api.lua and the registered surface\n')
    process.exit(0)
  }
  process.stderr.write('  FAIL  API.md is out of date with api.lua or the source.\n')
  process.stderr.write('        Run: npm run docs\n')
  // A diff is the useful part of the failure. Showing "they differ" makes
  // somebody diff it by hand; showing the difference makes them run the command.
  const a = current.split('\n')
  const b = text.split('\n')
  let shown = 0
  for (let i = 0; i < Math.max(a.length, b.length) && shown < 12; i++) {
    if (a[i] !== b[i]) {
      process.stderr.write(`        line ${i + 1}\n`)
      process.stderr.write(`          on disk: ${JSON.stringify(a[i])}\n`)
      process.stderr.write(`          generated: ${JSON.stringify(b[i])}\n`)
      shown++
    }
  }
  process.exit(1)
}

fs.writeFileSync(OUT, text)
process.stdout.write(`wrote ${path.relative(ROOT, OUT)} `
  + `(${Object.keys(api.exports || {}).length} exports, `
  + `${Object.keys(events).length} events)\n`)